services:
  postgres:
    image: postgres:16
    container_name: translog-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: translog
    ports:
      - "5432:5432"
    volumes:
      - translog_postgres_data:/var/lib/postgresql/data

volumes:
  translog_postgres_data: